import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import ParticleComponent from "./components/Particles";
import React from "react";
import { Avatar } from "@nextui-org/react";
import { Card, Grid, Text, Divider, Button, Row } from "@nextui-org/react";
import Stack from '@mui/material/Stack';
import Snackbar from '@mui/material/Snackbar';
import MuiAlert from '@mui/material/Alert';
export default function Home() {
  const [blogs, setBlogs] = React.useState([]);
  React.useEffect(() => {
    fetch("http://localhost:3000/api/blogs")
      .then((a) => {
        return a.json(JSON);
      })
      .then((data) => {
        console.log(data);
        setBlogs(data);
      });
  }, []);
  const Alert = React.forwardRef(function Alert(props, ref) {
  return <MuiAlert elevation={6} ref={ref} variant="filled" {...props} />;
});

  const [open, setOpen] = React.useState(false);

  const handleClick = () => {
    setOpen(true);
  };

  const handleClose = (event, reason) => {
    if (reason === 'clickaway') {
      return;
    }

    setOpen(false);
  };

  return (
    <div className={styles.container}>
      <ParticleComponent />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span className="text-blue-800">Next.js Blog!</span>
        </h1>

        <p className={styles.description}>
          Get started by reading our{" "}
          <code className={styles.code}>blog.js</code>
        </p>
        <div className={styles.grid}>
          {blogs.map((items) => {
            return (
              <Link href={`./components/blog/${items.slug}`} key={items.author}>
                <Card hoverable css={{ mw: "330px" }} className="my-2 mx-2">
                  <Card.Header>
                    <h5>
                    <Text b>{items.title}</Text>
                    </h5>
                  </Card.Header>
                  <Divider />
                  <Card.Body css={{ py: "$10" }}>
                    <Avatar pointer color="gradient" bordered stacked src={items.authorimage}></Avatar>
                    <Text b>By {items.author}</Text>
                    <Text>
                      Click the button given below and click on the card to read
                      the awesome content with complete satisfaction and easy to
                      understand
                    </Text>
                  </Card.Body>
                  <Divider />
                  <Card.Footer>
                    <Row justify="flex-end">
                      <Button size="sm" light onClick={handleClick}>
                        Upvote 
                      </Button>
                      <Link href={`./components/blog/${items.slug}`}>
                        <Button size="sm">Read more</Button>
                      </Link>
                    </Row>
                  </Card.Footer>
                </Card>
              </Link>
            );
          })}
        </div>
      </main>
      <footer className={styles.footer}>
        <div>
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </div>
      </footer>
      <Snackbar open={open} autoHideDuration={6000} onClose={handleClose}>
        <Alert onClose={handleClose} severity="success" sx={{ width: '100%' }}>
          You upvote this post thank you
        </Alert>
      </Snackbar>
    </div>
  );
}
